# For puppetlabs_spec_helper documentation - see http://github.com/puppetlabs/puppetlabs_spec_helper

fixtures:
# repositories:
#   stdlib: 'git://github.com/puppetlabs/puppetlabs-stdlib'
  symlinks:
    rtbbidder/files: '../../../../files'
    rtbbidder/manifests: '../../../../manifests'
    rtbbidder/templates: '../../../../templates'
    repo/files: '../../../../../repo/files'
    repo/manifests: '../../../../../repo/manifests'
    repo/templates: '../../../../../repo/templates'
    jdk/files: '../../../../../jdk/files'
    jdk/manifests: '../../../../../jdk/manifests'
    jdk/templates: '../../../../../jdk/templates'
    tomcat/files: '../../../../../tomcat/files'
    tomcat/manifests: '../../../../../tomcat/manifests'
    tomcat/templates: '../../../../../tomcat/templates'    
    bidder/files: '../../../../../bidder/files'
    bidder/manifests: '../../../../../bidder/manifests'
    bidder/templates: '../../../../../bidder/templates'
    scribe/files: '../../../../../scribe/files'
    scribe/manifests: '../../../../../scribe/manifests'
    scribe/templates: '../../../../../scribe/templates'
